package disasterdata;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jacob
 */
public class PersonFrame extends javax.swing.JFrame {

    /**
     * Creates new form PersonFrame
     */
    private final Database db;
    private final int id;
    private HashMap<String, Integer> list;
    private HashMap<String, Integer> orgs;

    public PersonFrame(Database db, int id) {
        this.db = db;
        this.id = id;
        initComponents();
        civilian_button.setSelected(true);
        worker_button.setSelected(false);
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        loadCounties(id);
        loadOrgs(id);
    }

    private void loadCounties(int disaster) {
        try {
            ResultSet disasterSet = db.query("SELECT `id`, `name` FROM `affected_county` WHERE  `disaster_id`=" + id + ";");

            list = new HashMap<>();
            while (disasterSet.next()) {
                list.put(disasterSet.getString("name"), disasterSet.getInt("id"));

                county_dropdown.addItem(disasterSet.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadOrgs(int disaster) {
        try {
            ResultSet disasterSet = db.query("SELECT `id`, `name` FROM `disaster_org` WHERE `disaster_id`=" + id + ";");

            orgs = new HashMap<>();
            while (disasterSet.next()) {
                orgs.put(disasterSet.getString("name"), disasterSet.getInt("id"));

                org_dropdown.addItem(disasterSet.getString("name"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(Welcome_Page.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        civilian_button = new javax.swing.JRadioButton();
        worker_button = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name_textField = new javax.swing.JTextField();
        age_textField = new javax.swing.JTextField();
        sex_dropdown = new javax.swing.JComboBox<>();
        county_dropdown = new javax.swing.JComboBox<>();
        ssn_textField = new javax.swing.JTextField();
        add_button = new javax.swing.JButton();
        continue_button = new javax.swing.JButton();
        finished_button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        status_dropdown = new javax.swing.JComboBox<>();
        last_location_textField = new javax.swing.JTextField();
        status_label = new javax.swing.JLabel();
        last_location_label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        position_label = new javax.swing.JLabel();
        salary_label = new javax.swing.JLabel();
        org_label = new javax.swing.JLabel();
        position_textField = new javax.swing.JTextField();
        salary_textField = new javax.swing.JTextField();
        org_dropdown = new javax.swing.JComboBox<>();

        jLabel7.setText("jLabel7");

        setTitle("Add Civilian/Worker");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ButtonGroup group = new ButtonGroup();
        group.add(civilian_button);
        civilian_button.setSelected(true);
        civilian_button.setText("Civilian");
        civilian_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                civilian_buttonMouseClicked(evt);
            }
        });
        civilian_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilian_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(civilian_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, -1, -1));

        group.add(worker_button);
        worker_button.setText("Worker");
        worker_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                worker_buttonMouseClicked(evt);
            }
        });
        worker_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worker_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(worker_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 19, -1, -1));

        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setText("Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabel4.setText("Sex");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel5.setText("County");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel6.setText("SSN");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        getContentPane().add(name_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 250, -1));
        getContentPane().add(age_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 250, -1));

        sex_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F", "O" }));
        getContentPane().add(sex_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, -1));

        getContentPane().add(county_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 250, -1));
        getContentPane().add(ssn_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 250, -1));

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 75, -1));

        continue_button.setText("Continue");
        continue_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continue_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(continue_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        finished_button.setText("Finished");
        getContentPane().add(finished_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 75, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        status_dropdown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alive", "Diseased", "Unknown", "Hospitalized" }));
        jPanel2.add(status_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 250, -1));
        jPanel2.add(last_location_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 250, -1));

        status_label.setText("Status");
        jPanel2.add(status_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        last_location_label.setText("Last Location");
        jPanel2.add(last_location_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 340, 100));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        position_label.setText("Position");
        jPanel1.add(position_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        salary_label.setText("Salary");
        jPanel1.add(salary_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        org_label.setText("Organization");
        jPanel1.add(org_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        position_textField.setEditable(false);
        jPanel1.add(position_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 250, -1));

        salary_textField.setEditable(false);
        jPanel1.add(salary_textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 250, -1));

        org_dropdown.setEnabled(false);
        jPanel1.add(org_dropdown, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 390, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void civilian_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilian_buttonActionPerformed

    }//GEN-LAST:event_civilian_buttonActionPerformed

    private void worker_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worker_buttonActionPerformed

    }//GEN-LAST:event_worker_buttonActionPerformed

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        boolean error = false;

        if (name_textField.getText().equals("")) {
            error = true;
        }
        if (age_textField.getText().equals("")) {
            error = true;
        }
        if (sex_dropdown.getSelectedItem().toString().equals("")) {
            error = true;
        }
        if (county_dropdown.getSelectedItem().toString().equals("")) {
            error = true;
        }
        if (ssn_textField.getText().equals("")) {
            error = true;
        }

        if (error) {
            JOptionPane.showMessageDialog(this, "Fields cannot be left empty!");
            return;
        }

        boolean number = true;

        try {
            Integer.parseInt(age_textField.getText());
            Integer.parseInt(ssn_textField.getText());
        } catch (NumberFormatException e) {
            number = false;
        }

        if (!number) {
            JOptionPane.showMessageDialog(this, "Age and SSN must both be numbers!");
            return;
        }

        String name = name_textField.getText();
        int age = Integer.parseInt(age_textField.getText());
        String sex = sex_dropdown.getSelectedItem().toString();
        int county = list.get(county_dropdown.getSelectedItem().toString());
        int ssn = Integer.parseInt(ssn_textField.getText());

        if (db.execute("INSERT INTO `person` (`ssn`, `name`, `age`, `sex`, `county_id`, `disaster_id`) VALUES ('" + ssn + "', '" + name + "', '" + age + "', '" + sex + "', '" + county + "', '" + id + "')")) {
            JOptionPane.showMessageDialog(this, "Successfully added person!");
        }

        if (civilian_button.isSelected()) {
            String status = status_dropdown.getSelectedItem().toString();
            String last = last_location_textField.getText();

            if (db.execute("INSERT INTO `civilian` (`ssn`, `last_location`, `status`) VALUES ('" + ssn + "', '" + last + "', '" + status + "')")) {
                JOptionPane.showMessageDialog(this, "Successfully added civilian!");
            }
        } else if (worker_button.isSelected()) {
            String position = position_textField.getText();
            int salary = Integer.parseInt(salary_textField.getText());
            int org = orgs.get((String) org_dropdown.getSelectedItem());

            if (db.execute("INSERT INTO `disaster_worker` (`ssn`, `salary`, `org_id`, `position`) VALUES ('" + ssn + "', '" + salary + "', '" + org + "', '" + position + "')")) {
                JOptionPane.showMessageDialog(this, "Successfully added disaster worker!");
            }
        }
        clear();
    }//GEN-LAST:event_add_buttonActionPerformed

    private void continue_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continue_buttonActionPerformed
        PropertyFrame pr = new PropertyFrame(db, id);
        setVisible(false);
        pr.setVisible(true);
    }//GEN-LAST:event_continue_buttonActionPerformed

    private void civilian_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_civilian_buttonMouseClicked
        System.out.println("disasterdata.PersonFrame.civilian_buttonMouseClicked()");
        worker_button.setSelected(false);

        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
        status_dropdown.setEnabled(true);
        last_location_textField.setEditable(true);
        position_textField.setEditable(false);
        salary_textField.setEditable(false);
        org_dropdown.setEnabled(false);
    }//GEN-LAST:event_civilian_buttonMouseClicked

    private void worker_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_worker_buttonMouseClicked
        System.out.println("disasterdata.PersonFrame.worker_buttonMouseClicked()");

        jPanel2.setVisible(false);
        jPanel1.setVisible(true);
        civilian_button.setSelected(false);
        status_dropdown.setEnabled(false);
        last_location_textField.setEditable(false);
        position_textField.setEditable(true);
        salary_textField.setEditable(true);
        org_dropdown.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_worker_buttonMouseClicked

    private void clear() {
        age_textField.setText("");
        last_location_textField.setText("");
        position_textField.setText("");
        salary_textField.setText("");
        name_textField.setText("");
        ssn_textField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JTextField age_textField;
    private javax.swing.JRadioButton civilian_button;
    private javax.swing.JButton continue_button;
    private javax.swing.JComboBox<String> county_dropdown;
    private javax.swing.JButton finished_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel last_location_label;
    private javax.swing.JTextField last_location_textField;
    private javax.swing.JTextField name_textField;
    private javax.swing.JComboBox<String> org_dropdown;
    private javax.swing.JLabel org_label;
    private javax.swing.JLabel position_label;
    private javax.swing.JTextField position_textField;
    private javax.swing.JLabel salary_label;
    private javax.swing.JTextField salary_textField;
    private javax.swing.JComboBox<String> sex_dropdown;
    private javax.swing.JTextField ssn_textField;
    private javax.swing.JComboBox<String> status_dropdown;
    private javax.swing.JLabel status_label;
    private javax.swing.JRadioButton worker_button;
    // End of variables declaration//GEN-END:variables
}
